/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent

group "com.github.marlonlom"
version "1.0.0"

//mainClassName = "com.github.marlonlom.utilities.elapsed_time.ElapsedTimes"

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.3.72"
    `java-library`
    id("com.adarshr.test-logger") version "2.1.0"
    application
    maven
}

repositories {
    jcenter()
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    withJavadocJar()
    withSourcesJar()
}

tasks {
    jar {
        manifest {
            attributes(
                mapOf("Implementation-Title" to project.name,
                      "Implementation-Version" to "1.0.0")
            )
        }
    }
}

task("writeNewPom") {
    doLast {
        maven.pom {
            withGroovyBuilder {
                "project" {
                    setProperty("groupId", "com.github.marlonlom")
                    setProperty("inceptionYear", "2020")
                    setProperty("packaging", "jar")
                    setProperty("description", "Kotlin utility library for, given a start and a end dates, obtain the elapsed time between the two dates in terms of years, months and days.")
                    setProperty("version", "1.0.0")
                    setProperty("url", "https://github.com/marlonlom/elapsed_times")
                    "developers" {
                        "developer" {
                            setProperty("id", "marlonlom")
                            setProperty("name", "Marlon López")
                            setProperty("email", "malm.gm@gmail.com")
                            setProperty("roles", listOf("developer"))
                        }
                    }
                    "licenses" {
                        "license" {
                            setProperty("name", "The Apache Software License, Version 2.0")
                            setProperty("url", "http://www.apache.org/licenses/LICENSE-2.0.txt")
                            setProperty("distribution", "repo")
                        }
                    }
                    "scm" {
                        setProperty("connection", "git@github.com:marlonlom/elapsed_times.git")
                        setProperty("developerConnection", "git@github.com:marlonlom/elapsed_times.git")
                        setProperty("tag", "HEAD")
                        setProperty("url", "https://github.com/marlonlom/elapsed_times")
                    }
                }
            }
        }.writeTo("${buildDir}/poms/pom.xml")
    }
}